version: "3.3"
services:
    dockerapp:
        build: .
        ports: 
          - 8100:8100
        volumes: 
          - ./docs:/app
        environment:
          - REDIS_HOST=redis-server
    redis-server:
        image: redis:3.2.0
        