version: '3.0'
 ## ports <EXPOSED PORT>:<PORT INSIDE DOCKER>
services:
  my-registry:
    image: registry:latest
    container_name: my-registry
    volumes:
      - registry:/var/lib/registry
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - REGISTRY_HTTP_RELATIVEURLS=true

volumes:
  registry: