version: '3.0'
 ## ports <EXPOSED PORT>:<PORT INSIDE DOCKER>
services:
  my-registry:
    image: registry:latest
    container_name: my-registry
    volumes:
      - ./registrydata:/data #host location:container location
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - REGISTRY_HTTP_RELATIVEURLS=true
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data # tell the registry to store at /data



  #http://localhost:5000/v2/_catalog