version: '3.1'
services:
    jenkins:
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        image: donhenton/jenkins-docker-master
        environment:
            - 'JAVA_OPTS=-Djavax.net.ssl.trustStore=/var/jenkins_home/certs/cacerts.jks -Djavax.net.ssl.trustStorePassword=changeit'
           
        volumes:
            - ~/ssl-installs/keystore_create:/etc/jenkins
            - ~/docker_series/jenkins_home:/var/jenkins_home # map jenkins home to a folder on your host

    jenkins-slave:
        container_name: jenkins-slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'

        image: donhenton/jenkins-master-slave 
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            #- /home/jenkins:/home/jenkins # Avoid mysql volume mount issue, host entry (may be relative):inner container folder
            - /var/lib/jenkins:/home/jenkins # on the mac this may need to be mapped in Docker -> Preferences -> File Sharing
        depends_on:
            - jenkins
    nexus_repo:
        ports:
            - '9081:8081'
        image: sonatype/nexus3 
        volumes:
            - ~/docker_series/nexus_repo:/nexus-data
        environment:
            - 'INSTALL4J_ADD_VM_PARAMS=-Xms1200m -Xmx1200m -XX:MaxDirectMemorySize=2g -Djavax.net.ssl.trustStore=/nexus-data/certs/cacerts.jks -Djavax.net.ssl.trustStorePassword=changeit'
   
        restart: unless-stopped
               
    my-registry:
        image: registry:latest
        container_name: my-registry
        volumes:
            - ./registrydata:/data #host location:container location
        ports:
            - "5000:5000"
        restart: unless-stopped
        environment:
            - REGISTRY_HTTP_RELATIVEURLS=true #needed for internal cert issues not needed in sane environment
            - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data # tell the registry to store at /data


# The Line# 18 is significant here as the mounted volume 
# will help fix the docker in docker volume mount issue. Its covered well in our previous article here

#http://localhost:5000/v2/_catalog docker registry
#http://localhost:8080 jenkins
